server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false


spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: "*"
#  endpoint:
#    health:
#      show-details: always